#  RESOLV_INCLUDE_DIRS - where to find header files.
#  RESOLV_LIBRARIES    - List of libraries when using resolv.
#  RESOLV_FOUND        - True if resolv found.

IF (RESOLV_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(RESOLV_FIND_QUIETLY TRUE)
ENDIF (RESOLV_INCLUDE_DIRS)

FIND_PATH(RESOLV_INCLUDE_DIR resolv.h HINTS ${RESOLV_INCLUDEDIR})
FIND_LIBRARY(RESOLV_LIBRARY NAMES resolv HINTS ${RESOLV_LIBDIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(RESOLV DEFAULT_MSG RESOLV_LIBRARY RESOLV_INCLUDE_DIR)

IF(RESOLV_FOUND)
  SET( RESOLV_LIBRARIES ${RESOLV_LIBRARY} )
  SET( RESOLV_INCLUDE_DIRS ${RESOLV_INCLUDE_DIR} )
ELSE(RESOLV_FOUND)
  SET( RESOLV_LIBRARIES )
  SET( RESOLV_INCLUDE_DIRS )
ENDIF(RESOLV_FOUND)

MARK_AS_ADVANCED( RESOLV_LIBRARIES RESOLV_INCLUDE_DIRS )
