#  IDN2_INCLUDE_DIRS - where to find header files.
#  IDN2_LIBRARIES    - List of libraries when using idn2.
#  IDN2_FOUND        - True if idn2 found.

IF (IDN2_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(IDN2_FIND_QUIETLY TRUE)
ENDIF (IDN2_INCLUDE_DIRS)

find_package(PkgConfig)
pkg_search_module(IDN2 libidn2)

FIND_PATH(IDN2_INCLUDE_DIR idn2.h HINTS ${IDN2_INCLUDEDIR})
FIND_LIBRARY(IDN2_LIBRARY NAMES idn2 HINTS ${IDN2_LIBDIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IDN2 DEFAULT_MSG IDN2_LIBRARY IDN2_INCLUDE_DIR)

IF(IDN2_FOUND)
  SET( IDN2_LIBRARIES ${IDN2_LIBRARY} )
  SET( IDN2_INCLUDE_DIRS ${IDN2_INCLUDE_DIR} )
ELSE(IDN2_FOUND)
  SET( IDN2_LIBRARIES )
  SET( IDN2_INCLUDE_DIRS )
ENDIF(IDN2_FOUND)

MARK_AS_ADVANCED( IDN2_LIBRARIES IDN2_INCLUDE_DIRS )
