#  NETTLE_INCLUDE_DIRS - where to find header files.
#  NETTLE_LIBRARIES    - List of libraries when using nettle.
#  NETTLE_FOUND        - True if nettle found.

IF (NETTLE_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(NETTLE_FIND_QUIETLY TRUE)
ENDIF (NETTLE_INCLUDE_DIRS)

find_package(PkgConfig)
pkg_search_module(NETTLE nettle)

FIND_PATH(NETTLE_INCLUDE_DIR nettle/md5.h HINTS ${NETTLE_INCLUDEDIR})
FIND_LIBRARY(NETTLE_LIBRARY NAMES nettle HINTS ${NETTLE_LIBDIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NETTLE DEFAULT_MSG NETTLE_LIBRARY NETTLE_INCLUDE_DIR)

IF(NETTLE_FOUND)
  SET( NETTLE_LIBRARIES ${NETTLE_LIBRARY} )
  SET( NETTLE_INCLUDE_DIRS ${NETTLE_INCLUDE_DIR} )
ELSE(NETTLE_FOUND)
  SET( NETTLE_LIBRARIES )
  SET( NETTLE_INCLUDE_DIRS )
ENDIF(NETTLE_FOUND)

MARK_AS_ADVANCED( NETTLE_LIBRARIES NETTLE_INCLUDE_DIRS )
