#  CAP_INCLUDE_DIRS - where to find header files.
#  CAP_LIBRARIES    - List of libraries when using cap.
#  CAP_FOUND        - True if cap found.

IF (CAP_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(CAP_FIND_QUIETLY TRUE)
ENDIF (CAP_INCLUDE_DIRS)

find_package(PkgConfig)
pkg_search_module(CAP libcap)

FIND_PATH(CAP_INCLUDE_DIR sys/capability.h HINTS ${CAP_INCLUDEDIR})
FIND_LIBRARY(CAP_LIBRARY NAMES cap HINTS ${CAP_LIBDIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CAP DEFAULT_MSG CAP_LIBRARY CAP_INCLUDE_DIR)

IF(CAP_FOUND)
  SET( CAP_LIBRARIES ${CAP_LIBRARY} )
  SET( CAP_INCLUDE_DIRS ${CAP_INCLUDE_DIR} )
ELSE(CAP_FOUND)
  SET( CAP_LIBRARIES )
  SET( CAP_INCLUDE_DIRS )
ENDIF(CAP_FOUND)

MARK_AS_ADVANCED( CAP_LIBRARIES CAP_INCLUDE_DIRS )
