#  GCRYPT_INCLUDE_DIRS - where to find header files.
#  GCRYPT_LIBRARIES    - List of libraries when using gcrypt.
#  GCRYPT_FOUND        - True if gcrypt found.

IF (GCRYPT_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(GCRYPT_FIND_QUIETLY TRUE)
ENDIF (GCRYPT_INCLUDE_DIRS)

# look for libgcrypt-config
FIND_PROGRAM(LIBGCRYPTCONFIG_EXECUTABLE NAMES ${LIBGCRYPT_CONFIG})
IF(LIBGCRYPTCONFIG_EXECUTABLE)
    EXECUTE_PROCESS(COMMAND ${LIBGCRYPTCONFIG_EXECUTABLE} --libs RESULT_VARIABLE _return_VALUE OUTPUT_VARIABLE GCRYPT_LIBRARY OUTPUT_STRIP_TRAILING_WHITESPACE)
ELSE(LIBGCRYPTCONFIG_EXECUTABLE)
    FIND_LIBRARY(GCRYPT_LIBRARY NAMES gcrypt)
ENDIF(LIBGCRYPTCONFIG_EXECUTABLE)

FIND_PATH(GCRYPT_INCLUDE_DIR gcrypt.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GCRYPT DEFAULT_MSG GCRYPT_LIBRARY GCRYPT_INCLUDE_DIR)

IF(GCRYPT_FOUND)
  SET( GCRYPT_LIBRARIES ${GCRYPT_LIBRARY} )
  SET( GCRYPT_INCLUDE_DIRS ${GCRYPT_INCLUDE_DIR} )
ELSE(GCRYPT_FOUND)
  SET( GCRYPT_LIBRARIES )
  SET( GCRYPT_INCLUDE_DIRS )
ENDIF(GCRYPT_FOUND)

MARK_AS_ADVANCED( GCRYPT_LIBRARIES GCRYPT_INCLUDE_DIRS )
